### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by onemoongit** [onemoongit/BoxOffice#1]
- 애플 프레임워크만 사용하기
- 이미지는 백그라운드에서 다운받아서 표시

## list view
- [ ] Table View & Collection View -> tab 으로 나누기 
- [ ] 화면에 정보들 표시
  - 싱글턴 패턴을 이용해보기
- [ ] 정렬한 기준을 타이틀에 보여주기
- [ ] 네비게이션 아이템을 통해서 영화 정렬하기
  - 탭바를 변경해도 변경된 기준은 그대로 남아있어야 한다.
- [ ] Table View & Collection View 아래로 당겼을 경우 새로고침
- [ ] 해당 셀을 누를 경우 상세화면 detail view 넘어가기

## detail view 
- [ ] 영화 상세화면 구성 
- [ ] 한줄평 리스트형식으로 구성
- [ ] 별점 표시 어떻게 해야할지 생각해보기

## additional point
- [ ] 네트워크 동작 중 상태표시줄 or 인디케이터
- [ ] 데이터 수신 실패 시 알림창으로 안내 
  - 참고로 HIG 잘 따를 것 ! ( 알림은 종료 되었다가 켜졌을 때 사라져야함 )
